trigger:
  - main

pool:
  vmImage: "ubuntu-latest"

jobs:
  - job: vibank_ui_job
    variables:
      environment: production
      buildConfiguration: "Release"
      workingDirectory: Web/viBank-Web/viBank-Ui/vibank
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: "18.x"
        displayName: "Install Nodejs"
      - script: |
          cd $(workingDirectory)
          npm ci
        displayName: "Npm CI"

      - task: NodeTool@0
        inputs:
          versionSpec: "18.x"
        displayName: "NPM RUN BUILD"
      - script: |
          cd $(workingDirectory)
          ls -la
          npm run build

      - task: ArchiveFiles@2
        displayName: "Archive built ui files"
        inputs:
          rootFolderOrFile: "$(Build.SourcesDirectory)Web/viBank-Web/viBank-Ui/vibank/out"
          includeRootFolder: false
          archiveType: "zip"
          archiveFile: "$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip"
          replaceExistingArchive: true

      - task: PublishPipelineArtifact@1
        displayName: "Publish Ui Artifacts"
        inputs:
          targetPath: "$(Build.ArtifactStagingDirectory)/vibank-ui-$(Build.BuildId).zip"
          artifact: "vibank-ui"
      - script: |
          cd ui/out
        displayName: "UI Copy static file to out folder"
  - job: api_job
    steps:
      - task: DotNetCoreCLI@2
        inputs:
          command: "build"
          projects: "$(Build.SourcesDirectory)/Web/viBank-Web/viBank-Api/viBank-Api/viBank-Api.csproj"

      - task: DotNetCoreCLI@2
        displayName: "Run API Tests"
        inputs:
          command: "test"
          projects: "$(Build.SourcesDirectory)/Web/viBank-Web/viBank-Api/viBankApiTests/viBankApiTests.csproj"
          publishTestResults: true

      - task: DotNetCoreCLI@2
        inputs:
          command: "publish"
          projects: "$(Build.SourcesDirectory)/viBank-Web/viBank-Api/viBank-Api"
          arguments: "--output $(Build.SourcesDirectory)/Web/viBank-Web/viBank-Api/viBank-Api/bin/Release"
          zipAfterPublish: false
          modifyOutputPath: false

      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: "$(Build.SourcesDirectory)/Web/viBank-Web/viBank-Api/viBank-Api/bin/Release"
          includeRootFolder: false
          archiveType: "zip"
          archiveFile: "$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip"
          replaceExistingArchive: true

      - task: PublishPipelineArtifact@1
        displayName: "Publish API Artifact"
        inputs:
          targetPath: "$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip"
          artifact: "vibank-api"

  - job: vibank_db_job
    steps:
      - task: DotNetCoreCLI@2
        displayName: "Build Db Dacpac File"
        inputs:
          command: "build"
          projects: "$(Build.SourcesDirectory)/dbproj/vibankDb/vibankDb.sqlproj"
          arguments: "/p:NetCoreBuild=true"

      - task: ArchiveFiles@2
        displayName: "Archive DB build files"
        inputs:
          rootFolderOrFile: "$(Build.SourcesDirectory)/dbproj/vibankDb/bin/Debug"
          includeRootFolder: false
          archiveType: zip
          archiveFile: "$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip"
          replaceExistingArchive: true

      - task: PublishPipelineArtifact@1
        displayName: "Publish DB Artifact"
        inputs:
          targetPath: "$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip"
          artifactName: vibank-db
