trigger:
  - main

pool:
  vmImage: "ubuntu-latest"

jobs:
  - job: vibank_ui_job
    variables:
      environment: production
      buildConfiguration: "Release"
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: "18.x"
        displayName: "Install Nodejs"
      - script: |
          cd vibank
          npm install
          npm run build
        displayName: "Npm Run Build"

      - task: ArchiveFiles@2
        displayName: "Archive built ui files"
        inputs:
          rootFolderOrFile: "$(Build.SourcesDirectory)/Web/viBank-Web/viBank-Ui/vibank/out"
          includeRootFolder: false
          archiveType: "zip"
          archiveFile: "$(Build.ArtifactStagingDirectory)/vibank-ui-$(Build.BuildId).zip"
          replaceExistingArchive: true

      - task: PublishPipelineArtifact@1
        displayName: "Publish Ui Artifacts"
        inputs:
          targetPath: "$(Build.ArtifactStagingDirectory)/vibank-ui-$(Build.BuildId).zip"
          artifact: "vibank-ui"

  - job: api_job
    steps:
      - script: dotnet build --configuration $(buildConfiguration)
      - task: DotNetCoreCLI@2
        displayName: "dotnet build $(buildConfiguration)"
        inputs:
          command: "publish"
          arguments: "--configuration $(buildConfiguration)"
          projects: "$(Build.SourcesDirectory)/viBank-Api/viBank-Api.csproj"

      - task: DotNetCoreCLI@2
        inputs:
          command: "publish"
          publishWebProjects: true
      - task: AzureWebApp@1
        inputs:
          azureSubscription: "Azure subscription 1"
          appType: "webAppLinux"
          appName: "vibank-api"
          package: "$(Build.ArtifactStagingDirectory)/**/*.zip"

      - task: PublishPipelineArtifact@1
        displayName: "Publish API Artifact"
        inputs:
          targetPath: "$(Build.ArtifactStagingDirectory)/vibank-api-$(Build.BuildId).zip"
          artifact: "vibank-api"

  - job: vibank_db_job
    steps:
      - task: DotNetCoreCLI@2
        displayName: "Build Db Dacpac File"
        inputs:
          command: "build"
          projects: "**/*.sqlproj"
          arguments: "/p:NetCoreBuild=true"
          workingDirectory: "$(Build.SourcesDirectory)/dbproj/SqlDatabase"
      - task: ArchiveFiles@2
        displayName: "Archive DB build files"
        inputs:
          rootFolderOrFile: "$(Build.SourcesDirectory)/dbproj/bin/Debug"
          includeRootFolder: false
          archiveType: zip
          archiveFile: "$(Build.ArtifactStagingDirectory)/vibank-db-$(Build.BuildId).zip"
          replaceExistingArchive: true

      - task: PublishPipelineArtifact@1
        displayName: "Publish DB Artifact"
        inputs:
          targetPath: "$(Build.ArtifactStagingDirectory)/vibank-db-$(Build.BuildId).zip"
          artifactName: vibank-db
