version: 2.1

orbs:
  node: circleci/node@5.0.0
  aws-eks: circleci/aws-eks@1.1.0
  
executors:
  docker-executor:
    docker:
      - image: cimg/base:stable
  docker-flutter-executor:
    docker:
      - image: gmemstr/flutter-fastlane-android:29.0
jobs:
  # build the api
  build-backend:
    executor: docker-executor
    steps:
      - checkout
      - run: 
          name: Restore NuGet packages
          command: dotnet restore viBank-Web/viBank-Api
      - run:
          name: Build .NET project
          command: dotnet build viBank-Web/viBank-Api --configuration Release
      - save_cache:
          key: v1-dotnet-{{ .Branch }}-{{ .Revision }}
          paths:
            - viBank-Web/viBank-Api/bin/Release
      
  #build the frontend 
  build-frontend:
    executor: docker-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-{{ .Branch }}-{{ checksum "viBank-Web/viBank-Ui/package-lock.json" }}
      - run: 
          name: Install Node.js dependencies
          command: npm install --prefix viBank-Web/viBank-Ui
      - save_cache:
          key: v1-npm-{{ .Branch }}-{{ .Revision }}
          paths:
            - viBank-Web/viBank-Ui/node_modules
      - run:
          name: Build React project
          command: npm run build --prefix viBank-Web/viBank-Ui
  #build the mobile-app
  build-mobile:
    executor: docker-flutter-executor
    environment:
      TERM: dumb
      _JAVA_OPTIONS: "-Xmx2048m -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m"'
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-flutter-{{ .Branch }}-{{ checksum "Mobile/viBank-Mobile/vibankapp/android/app/build.gradle" }}
      - run: echo "$PLAY_STORE_UPLOAD_KEY" | base64 --decode > key.jks
      - run: echo "$PLAY_STORE_UPLOAD_KEY_INFO" | base64 --decode > android/key.properties
      - run: cd android && fastlane beta
  # run flutter tests
  test-mobile:
    executor: docker-executor
    steps:
      - checkout
      - restore_cache:
          key: v1-flutter-{{ .Branch }}-{{ .Revision }}
      - run:
          name: Test Flutter project
          command: flutter test

  test-backend:
    executor: docker-executor
    steps:
      - checkout
      - restore_cache:
          key: v1-dotnet-{{ .Branch }}-{{ .Revision }}
      - run: 
          name: Test .NET project
          command: dotnet test viBank-Web/viBank-Api

  test-frontend:
    executor: docker-executor
    steps:
      - checkout
      - restore_cache:
          key: v1-npm-{{ .Branch }}-{{ .Revision }}
      - run: 
          name: Test React project
          command: npm test --prefix viBank-Web/viBank-Ui

  deploy-to-aws:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: your-cluster-name
      - run:
          name: Deploy to AWS EKS
          command: |
            #docker build -t your-aws-account.dkr.ecr.your-region.amazonaws.com/your-repo:latest .
           # docker push your-aws-account.dkr.ecr.your-region.amazonaws.com/your-repo:latest
            #kubectl set image deployment/your-deployment your-container=your-aws-account.dkr.ecr.your-region.amazonaws.com/your-repo:latest

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-backend
      - build-frontend
      - build-mobile
      - test-mobile
      - test-backend:
          requires:
            - build-backend
      - test-frontend:
          requires:
            - build-frontend
            - test-mobile
      - build-mobile:
          requires:
            - build-backend
            - build-frontend
      - deploy-to-aws:
          requires:
            - test-backend
            - test-frontend
           
