BEGIN
    TRANSACTION;
    SET IDENTITY_INSERT [DBO].[ATMS] ON;
    GO WITH AVAILABLEATMS AS (
        SELECT
            *
        FROM
            (VALUES (1,
            '758bb331-e613-46bb-82c4-9191ec2ee826',
            'TorontoCA',
            2000000.00,
            1,
            GETDATE(),
            0) ) AS VAL (ID,
            ATMID,
            LOCATION,
            AVAILABLEBALANCE,
            ISACTIVE,
            CREATEDDTM,
            ISDELETED)
    ) MERGE [DBO].[ATMS] AS TARGET USING AVAILABLEATMS AS SOURCE ON SOURCE.ID = TARGET.ID WHEN NOT MATCHED BY TARGET THEN
        INSERT (
            [ID],
            [ATMID],
            [LOCATION],
            [AVAILABLEBALANCE],
            [ISACTIVE],
            [CREATEDDTM],
            [ISDELETED]
        ) VALUES (
            SOURCE.[ID],
            SOURCE.[ATMID],
            SOURCE.[LOCATION],
            SOURCE.[AVAILABLEBALANCE],
            SOURCE.[ISACTIVE],
            SOURCE.[CREATEDDTM],
            SOURCE.[ISDELETED]
        )
            WHEN MATCHED THEN UPDATE SET TARGET.[ATMID] = SOURCE.[ATMID], TARGET.[LOCATION] = SOURCE.[LOCATION], TARGET.[AVAILABLEBALANCE] = SOURCE.[AVAILABLEBALANCE], TARGET.[ISACTIVE] = SOURCE.[ISACTIVE], TARGET.[CREATEDDTM] = SOURCE.[CREATEDDTM], TARGET.[ISDELETED] = SOURCE.[ISDELETED];
        GO SET IDENTITY_INSERT [DBO].[ATMS] OFF;
        COMMIT TRANSACTION;